/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * main.h — Shared types and extern declarations
 *
 * ONE INCH WONDER — Rev A-1 eND Controller Firmware
 * Target MCU: STM32U5A5RJT6 (Cortex-M33, 2MB Flash, 786KB SRAM)
 * Document: LCDRV-A1-FW-001 Rev A  |  2026-03-25
 *
 * Component deltas versus LCDRV-001 (STM32G0B1):
 *   Temperature:  TMP117 I2C digital sensor (replaces NTC + ADC)
 *   ND amplitude: AD5696R 16-bit DAC (replaces MCP4131 + AD9833)
 *   AC carrier:   STM32 TIM2 OC square wave + ADG1419 polarity switch
 *   Power supply: TPS65131 ±15V rails (enable/disable under fault)
 *   Op amp:       OPA2197 dual precision (replaces OPA548)
 *
 * USB CDC protocol is identical to LCDRV-001 — same kernel driver
 * and HAL wrapper are reused without modification.
 */

#ifndef MAIN_H
#define MAIN_H

#include <stdint.h>
#include <stdbool.h>

#include "FreeRTOS.h"
#include "semphr.h"

/* ── Firmware version ────────────────────────────────────────── */
#define FW_VERSION          0x0200   /* Rev A-1 = 2.0 */

/* ── STATUS register bits (same definition as LCDRV-001) ──────── */
#define STATUS_SETTLED      (1u << 0)
#define STATUS_DC_FAULT     (1u << 1)
#define STATUS_CAL_ACTIVE   (1u << 2)
#define STATUS_LUT_VALID    (1u << 3)
#define STATUS_TEMP_WARN    (1u << 4)
#define STATUS_LC_OPEN      (1u << 5)

/* ── LC drive limits (millivolts Vrms, square wave Vpeak = Vrms) ─ */
#define LC_VRMS_MIN_MV      1650u    /* minimum cell drive voltage  */
#define LC_VRMS_MAX_MV     15000u    /* maximum — TPS65131 +15V     */

/* ── Settle timing ───────────────────────────────────────────── */
#define SETTLE_TICKS        3u       /* × 10 ms control loop ticks  */

/* ── Temperature warning threshold ───────────────────────────── */
#define TEMP_WARN_DECIDEGC  400      /* 40.0 °C → STATUS_TEMP_WARN  */
#define TEMP_CRIT_DECIDEGC  550      /* 55.0 °C → disable drive      */

/* ── Shared ND state struct ──────────────────────────────────── */
typedef struct {
    int16_t  nd_target;         /* commanded ND level 0-255         */
    int16_t  nd_actual;         /* measured ND level  0-255         */
    uint8_t  mode;              /* 0=manual 1=auto-HAL 2=auto-MCU   */
    int16_t  temp_decidegc;     /* cell temperature × 10 °C         */
    uint8_t  status;            /* STATUS_* bitmask                 */
    uint8_t  ccm_idx;           /* CCM table index 0-60             */
    uint16_t dac_code;          /* current AD5696R DAC_A code       */
    int16_t  dc_offset_mv;      /* LC cell DC offset (monitor)      */
} nd_state_t;

/* ── HAL peripheral handles (defined in main.c, generated by CubeMX) */
extern I2C_HandleTypeDef hi2c1;    /* TMP117 */
extern I2C_HandleTypeDef hi2c2;    /* AD5696R */
extern ADC_HandleTypeDef hadc1;    /* DC offset monitor */
extern TIM_HandleTypeDef htim2;    /* AC carrier square wave */
extern USBD_HandleTypeDef hUsbDeviceFS;

/* ── FreeRTOS synchronisation primitives ─────────────────────── */
extern SemaphoreHandle_t g_i2c_mutex;     /* shared I2C bus lock  */
extern SemaphoreHandle_t g_state_mutex;   /* g_nd access lock     */
extern SemaphoreHandle_t g_usb_rx_sem;    /* USB RX ISR → task    */

/* ── Global ND state ─────────────────────────────────────────── */
extern nd_state_t g_nd;

#endif /* MAIN_H */
