/* SPDX-License-Identifier: GPL-2.0-only
 * main.h — LCDRV-001 STM32G0B1 shared types and global state
 * ONE INCH WONDER — LC Variable ND Filter Driver Firmware
 * Document: LCDRV-FW-001 Rev A  |  2026-03-24
 *
 * Prerequisites: generate base project with STM32CubeIDE / CubeMX:
 *   MCU:  STM32G0B1KET6 (LQFP-32)
 *   USB:  CDC device, FS
 *   SPI1: Master, Mode 1 (CPOL=0 CPHA=1), 10 MHz, software CS
 *   ADC1: CH0=PA0 (NTC), CH1=PA1 (output monitor), 12-bit, sw trigger
 *   RTOS: FreeRTOS (native API)
 */
#pragma once

#include "stm32g0xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"

/* ── Firmware version (BCD: 0x0100 = v1.0) ────────────────────── */
#define FW_VERSION          0x0100U

/* ── ND encoding (matches kernel driver + INTEGRATION_MAP.md) ──── *
 *   nd_stops = 1.10 + (ND_TARGET / 255.0) × 5.90                  *
 *   ND_TARGET = round((nd_stops - 1.10) / 5.90 × 255)             */
#define ND_TARGET_MIN       0U
#define ND_TARGET_MAX       255U
#define ND_TARGET_SAFE      0U    /* minimum gain — always safe on boot */

/* ── STATUS register bit masks ─────────────────────────────────── */
#define STATUS_SETTLED      (1U << 0)
#define STATUS_DC_FAULT     (1U << 1)
#define STATUS_CAL_ACTIVE   (1U << 2)
#define STATUS_LUT_VALID    (1U << 3)
#define STATUS_TEMP_WARN    (1U << 4)   /* cell temp > 40 °C */
#define STATUS_LC_OPEN      (1U << 5)

/* ── DC fault threshold ─────────────────────────────────────────── */
#define DC_FAULT_MV_THRESH  15          /* |mean| > 15 mV → fault   */

/* ── Shared firmware state (written by multiple tasks) ─────────── */
typedef struct {
    uint8_t  nd_target;         /* commanded ND (0-255 encoding)    */
    uint8_t  nd_actual;         /* achieved ND (same encoding)       */
    uint8_t  mode;              /* 0=manual 1=auto-HAL 2=auto-MCU 3=bypass */
    int16_t  temp_decidegc;     /* LC cell temperature ×10 (e.g. 245=24.5°C) */
    uint8_t  status;            /* STATUS_* bitmask                  */
    uint8_t  ccm_idx;           /* CCM table index (0-60)            */
    uint8_t  wiper_raw;         /* current MCP4131 wiper (diagnostics) */
    int16_t  dc_offset_mv;      /* signed DC offset in mV            */
} nd_state_t;

/* ── HAL peripheral handles (defined in main.c, generated by CubeMX) */
extern SPI_HandleTypeDef  hspi1;
extern ADC_HandleTypeDef  hadc1;

/* ── FreeRTOS handles ───────────────────────────────────────────── */
extern SemaphoreHandle_t  g_spi_mutex;   /* protects shared SPI1 bus  */
extern SemaphoreHandle_t  g_state_mutex; /* protects nd_state          */
extern SemaphoreHandle_t  g_usb_rx_sem;  /* signals USB Rx to usb_task */

/* ── Global firmware state ──────────────────────────────────────── */
extern volatile nd_state_t g_nd;

/* ── SPI GPIO helpers (software CS, defined in main.c) ─────────── */
void spi_cs_ad9833_assert(void);
void spi_cs_ad9833_deassert(void);
void spi_cs_mcp4131_assert(void);
void spi_cs_mcp4131_deassert(void);
