# SPDX-License-Identifier: GPL-2.0-only
# Makefile for Xiaomi USB-C Dock / Daughter Board driver

obj-$(CONFIG_XIAOMI_USB_DOCK)     += xiaomi_usb_dock.o
obj-$(CONFIG_XIAOMI_USB_DOCK)     += xiaomi_usb_dock_pd.o
