/* SPDX-License-Identifier: GPL-2.0-only
 * usb_cdc_handler.c — USB CDC packet receive, dispatch, and transmit
 *
 * Packet format (both directions):
 *   [cmd/reg : u8][val_lo : u8][val_hi : u8][checksum : u8 = XOR(0..2)]
 *
 * Called from interrupt: usb_cdc_on_rx()  (hook in usbd_cdc_if.c)
 * FreeRTOS task:         usb_task()        (priority HIGH, 512B stack)
 */

#include "usb_cdc_handler.h"
#include "main.h"
#include "nd_control.h"
#include "lut.h"
#include "usbd_cdc_if.h"    /* generated by CubeMX — provides CDC_Transmit_FS */
#include <string.h>

/* ── Private rx buffer (written by ISR, read by usb_task) ──────── */
static uint8_t  s_rx_buf[USB_PKT_LEN];
static uint32_t s_rx_len;

/* ─────────────────────────────────────────────────────────────── *
 * Checksum (XOR of bytes 0-2)                                     *
 * ─────────────────────────────────────────────────────────────── */
static uint8_t checksum(const uint8_t *b)
{
    return b[0] ^ b[1] ^ b[2];
}

/* ─────────────────────────────────────────────────────────────── *
 * Build and transmit a 4-byte response packet                     *
 * ─────────────────────────────────────────────────────────────── */
static void send_response(uint8_t reg, uint16_t value)
{
    uint8_t pkt[USB_PKT_LEN];
    pkt[0] = reg;
    pkt[1] = (uint8_t)(value & 0xFF);
    pkt[2] = (uint8_t)((value >> 8) & 0xFF);
    pkt[3] = checksum(pkt);
    CDC_Transmit_FS(pkt, USB_PKT_LEN);
}

/* ─────────────────────────────────────────────────────────────── *
 * Calibration state (simple state machine, host-paced)           *
 * ─────────────────────────────────────────────────────────────── */
static struct {
    bool     active;
    uint8_t  wiper_step;   /* current wiper position being swept (0-127) */
} s_cal;

/* ─────────────────────────────────────────────────────────────── *
 * Command dispatch                                                 *
 * ─────────────────────────────────────────────────────────────── */
static void dispatch(const uint8_t *pkt)
{
    uint8_t  cmd    = pkt[0];
    uint16_t val    = (uint16_t)pkt[1] | ((uint16_t)pkt[2] << 8);

    xSemaphoreTake(g_state_mutex, portMAX_DELAY);

    switch (cmd) {

    /* ── ND_TARGET write ──────────────────────────────────────── */
    case CMD_WRITE_TARGET:
        if (!(g_nd.status & STATUS_DC_FAULT)) {
            xSemaphoreGive(g_state_mutex);
            nd_set_target((uint8_t)(val & 0xFF));
            xSemaphoreTake(g_state_mutex, portMAX_DELAY);
            /* Replying with the new actual (will equal target after set) */
            send_response(CMD_WRITE_TARGET, g_nd.nd_actual);
        } else {
            send_response(CMD_WRITE_TARGET, g_nd.nd_actual);
        }
        break;

    /* ── ND_ACTUAL read ───────────────────────────────────────── */
    case CMD_READ_ACTUAL:
        send_response(CMD_READ_ACTUAL, g_nd.nd_actual);
        break;

    /* ── MODE write ──────────────────────────────────────────── */
    case CMD_WRITE_MODE:
        g_nd.mode = (uint8_t)(val & 0x03);
        send_response(CMD_WRITE_MODE, g_nd.mode);
        break;

    /* ── TEMP_C read ─────────────────────────────────────────── */
    case CMD_READ_TEMP:
        send_response(CMD_READ_TEMP, (uint16_t)g_nd.temp_decidegc);
        break;

    /* ── STATUS read ─────────────────────────────────────────── */
    case CMD_READ_STATUS:
        send_response(CMD_READ_STATUS, g_nd.status);
        break;

    /* ── CCM_IDX read ────────────────────────────────────────── */
    case CMD_READ_CCM_IDX:
        send_response(CMD_READ_CCM_IDX, g_nd.ccm_idx);
        break;

    /* ── WIPER_RAW read ──────────────────────────────────────── */
    case CMD_READ_WIPER:
        send_response(CMD_READ_WIPER, g_nd.wiper_raw);
        break;

    /* ── DC_OFFSET_MV read ───────────────────────────────────── */
    case CMD_READ_DC_OFFSET:
        send_response(CMD_READ_DC_OFFSET, (uint16_t)g_nd.dc_offset_mv);
        break;

    /* ── CAL_TRIGGER ─────────────────────────────────────────── */
    case CMD_WRITE_CAL_TRIG:
        if ((uint8_t)(val & 0xFF) == 0xCA) {
            s_cal.active     = true;
            s_cal.wiper_step = 0;
            g_nd.status |= STATUS_CAL_ACTIVE;
            /* Drive wiper to 0, wait host to page through steps */
            xSemaphoreGive(g_state_mutex);
            xSemaphoreTake(g_spi_mutex, portMAX_DELAY);
            mcp4131_set_wiper(0);
            g_nd.wiper_raw = 0;
            xSemaphoreGive(g_spi_mutex);
            xSemaphoreTake(g_state_mutex, portMAX_DELAY);
            send_response(CMD_WRITE_CAL_TRIG, 0xCA);
        }
        break;

    /* ── CAL_NEXT — advance wiper by 2, wait 200 ms ─────────── */
    case CMD_WRITE_CAL_NEXT:
        if (s_cal.active && (uint8_t)(val & 0xFF) == 0x01) {
            if (s_cal.wiper_step < 126)
                s_cal.wiper_step += 2;
            xSemaphoreGive(g_state_mutex);
            xSemaphoreTake(g_spi_mutex, portMAX_DELAY);
            mcp4131_set_wiper(s_cal.wiper_step);
            xSemaphoreGive(g_spi_mutex);
            HAL_Delay(200);   /* settle — OK in usb_task, no timing-critical work */
            xSemaphoreTake(g_state_mutex, portMAX_DELAY);
            g_nd.wiper_raw = s_cal.wiper_step;
            send_response(CMD_WRITE_CAL_NEXT, s_cal.wiper_step);
        }
        break;

    /* ── CAL_WRITE_LUT — burn flash ──────────────────────────── *
     * Host has already sent LUT data via (protocol TBD — see     *
     * INTEGRATION_MAP.md CALIBRATION_FLOW). For now this command  *
     * signals that the last chunk was written; firmware verifies  *
     * and marks LUT valid.                                        */
    case CMD_WRITE_CAL_LUT:
        if (s_cal.active && (uint8_t)(val & 0xFF) == 0xAA) {
            s_cal.active = false;
            g_nd.status &= (uint8_t)~STATUS_CAL_ACTIVE;
            /* lut_load() verifies flash and sets STATUS_LUT_VALID */
            xSemaphoreGive(g_state_mutex);
            bool ok = lut_load();
            xSemaphoreTake(g_state_mutex, portMAX_DELAY);
            send_response(CMD_WRITE_CAL_LUT, ok ? 1 : 0);
        }
        break;

    /* ── FW_VERSION read ─────────────────────────────────────── */
    case CMD_READ_FW_VER:
        send_response(CMD_READ_FW_VER, FW_VERSION);
        break;

    /* ── PING / heartbeat ────────────────────────────────────── */
    case CMD_PING:
        send_response(CMD_PING, FW_VERSION);
        break;

    default:
        /* Unknown command — echo back with 0xEE error marker */
        send_response(0xEE, cmd);
        break;
    }

    xSemaphoreGive(g_state_mutex);
}

/* ─────────────────────────────────────────────────────────────── *
 * ISR callback — called from USB interrupt context               *
 * Hook this into CDC_Receive_FS() in usbd_cdc_if.c:             *
 *   usb_cdc_on_rx(Buf, *Len);                                    *
 * ─────────────────────────────────────────────────────────────── */
void usb_cdc_on_rx(const uint8_t *buf, uint32_t len)
{
    if (len < USB_PKT_LEN)
        return;

    /* Copy exactly one packet (extra bytes ignored) */
    memcpy(s_rx_buf, buf, USB_PKT_LEN);
    s_rx_len = USB_PKT_LEN;

    /* Signal usb_task from ISR context */
    BaseType_t higher_prio_woken = pdFALSE;
    xSemaphoreGiveFromISR(g_usb_rx_sem, &higher_prio_woken);
    portYIELD_FROM_ISR(higher_prio_woken);
}

/* ─────────────────────────────────────────────────────────────── *
 * FreeRTOS task (priority HIGH, 512 B stack)                     *
 * ─────────────────────────────────────────────────────────────── */
void usb_task(void *arg)
{
    (void)arg;
    uint8_t pkt[USB_PKT_LEN];

    for (;;) {
        /* Block until ISR signals a new packet */
        if (xSemaphoreTake(g_usb_rx_sem, portMAX_DELAY) != pdTRUE)
            continue;

        memcpy(pkt, (const void *)s_rx_buf, USB_PKT_LEN);

        /* Verify checksum */
        if (pkt[3] != checksum(pkt))
            continue;   /* silently drop malformed packets */

        dispatch(pkt);
    }
}
