/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * main.c — Rev A-1 eND controller firmware entry point
 *
 * ONE INCH WONDER — Rev A-1 eND Controller Firmware
 * Target MCU: STM32U5A5RJT6 (Cortex-M33, 2MB Flash, 786KB SRAM)
 * Document: LCDRV-A1-FW-001 Rev A  |  2026-03-25
 *
 * FreeRTOS task layout:
 *   usb_task      PRIORITY 4  128W  — USB CDC RX dispatch
 *   control_task  PRIORITY 3   64W  — 10ms loop: DC monitor, ND tick, PID gate
 *   sensor_task   PRIORITY 2   64W  — 100ms loop: TMP117 read, TEMP_WARN
 *
 * Initialisation sequence (before vTaskStartScheduler):
 *   1. HAL_Init(), SystemClock_Config()   — CubeMX generated
 *   2. MX_GPIO_Init(), MX_I2C1_Init(), MX_I2C2_Init()
 *      MX_TIM2_Init(), MX_ADC1_Init(), MX_USB_DEVICE_Init()
 *   3. ad5696r_init()  — zero DAC, safe state
 *   4. tmp117_init()   — configure TMP117 one-shot
 *   5. lc_drive_init() — ensure ±15V rails off, timer stopped
 *   6. lut_load()      — validate flash LUT, set LUT_VALID status bit
 *   7. Create RTOS primitives and tasks
 *   8. vTaskStartScheduler()
 *
 * USB protocol is identical to LCDRV-001. Same kernel driver and HAL
 * wrapper are used without modification on the host side.
 */

#include "main.h"
#include "usb_device.h"

#include "tmp117_driver.h"
#include "ad5696r_driver.h"
#include "lc_drive.h"
#include "nd_control.h"
#include "dc_monitor.h"
#include "lut.h"

/* ── HAL peripheral handles (generated by CubeMX) ────────────── */
I2C_HandleTypeDef  hi2c1;    /* TMP117  */
I2C_HandleTypeDef  hi2c2;    /* AD5696R */
ADC_HandleTypeDef  hadc1;    /* DC offset monitor ADC */
TIM_HandleTypeDef  htim2;    /* AC carrier square wave */

/* ── FreeRTOS synchronisation ─────────────────────────────────── */
SemaphoreHandle_t g_i2c_mutex   = NULL;
SemaphoreHandle_t g_state_mutex = NULL;
SemaphoreHandle_t g_usb_rx_sem  = NULL;

/* ── Global ND state ─────────────────────────────────────────── */
nd_state_t g_nd = {
    .nd_target     = 0,
    .nd_actual     = 0,
    .mode          = 0,
    .temp_decidegc = 250,   /* 25.0 °C safe default until first read */
    .status        = 0,
    .ccm_idx       = 0,
    .dac_code      = 0,
    .dc_offset_mv  = 0,
};

/* ── Forward declarations for task functions ─────────────────── */
static void usb_task(void *arg);
static void control_task(void *arg);
static void sensor_task(void *arg);

/* ─────────────────────────────────────────────────────────────── *
 * main()                                                          *
 * ─────────────────────────────────────────────────────────────── */

int main(void)
{
    /* ── 1. HAL + clock init (CubeMX generated) ──────────────── */
    HAL_Init();
    SystemClock_Config();

    /* ── 2. Peripheral init (CubeMX generated) ───────────────── */
    MX_GPIO_Init();
    MX_I2C1_Init();    /* TMP117 bus */
    MX_I2C2_Init();    /* AD5696R bus */
    MX_ADC1_Init();    /* DC offset monitor */
    MX_TIM2_Init();    /* AC carrier (not started yet) */
    MX_USB_DEVICE_Init();

    /* ── 3. Hardware init — safe state before scheduler ─────── */
    ad5696r_init();    /* zero DAC — minimum LC drive */
    tmp117_init();     /* configure TMP117, set alert threshold */
    tmp117_set_alert_threshold(TEMP_CRIT_DECIDEGC);
    lc_drive_init();   /* ensure ±15V rails off, timer stopped */

    /* ── 4. Flash LUT validation ─────────────────────────────── */
    if (lut_load()) {
        g_nd.status |= STATUS_LUT_VALID;
    }

    /* ── 5. FreeRTOS primitives ──────────────────────────────── */
    g_i2c_mutex   = xSemaphoreCreateMutex();
    g_state_mutex = xSemaphoreCreateMutex();
    g_usb_rx_sem  = xSemaphoreCreateBinary();

    /* Check all primitives were created */
    if (!g_i2c_mutex || !g_state_mutex || !g_usb_rx_sem)
        Error_Handler();

    /* ── 6. Create tasks ─────────────────────────────────────── */
    if (xTaskCreate(usb_task,     "USB",     128, NULL, 4, NULL) != pdPASS ||
        xTaskCreate(control_task, "CTRL",     64, NULL, 3, NULL) != pdPASS ||
        xTaskCreate(sensor_task,  "SENS",     64, NULL, 2, NULL) != pdPASS) {
        Error_Handler();
    }

    /* ── 7. Start scheduler (never returns) ─────────────────── */
    vTaskStartScheduler();

    /* Should never reach here */
    Error_Handler();
    return 0;
}

/* ─────────────────────────────────────────────────────────────── *
 * FreeRTOS tasks                                                  *
 * ─────────────────────────────────────────────────────────────── */

/*
 * usb_task — waits on g_usb_rx_sem given by USB CDC RX ISR,
 * then dispatches the received 4-byte packet.
 * Defined in usb_cdc_handler.c (identical to LCDRV-001 version
 * except HAL_Delay → vTaskDelay bug is already fixed in Rev A).
 */
extern void usb_task_fn(void *arg);
static void usb_task(void *arg) { usb_task_fn(arg); }

/*
 * control_task — 10 ms periodic.
 *
 * Responsibilities:
 *   1. DC offset monitor: sample ADC, compute running mean, check fault
 *   2. ND settle timer: decrement, set STATUS_SETTLED at zero
 *   3. Gate PID task creation/deletion based on mode
 */
static TaskHandle_t s_pid_task_handle = NULL;
extern void pid_task_fn(void *arg);

static void control_task(void *arg)
{
    TickType_t last_wake = xTaskGetTickCount();
    (void)arg;

    for (;;) {
        vTaskDelayUntil(&last_wake, pdMS_TO_TICKS(10));

        /* ── DC monitor ────────────────────────────────────── */
        dc_monitor_sample();
        if (dc_monitor_check()) {
            /* Fault: shut down drive, set status bit */
            xSemaphoreTake(g_state_mutex, portMAX_DELAY);
            g_nd.status |= STATUS_DC_FAULT;
            xSemaphoreGive(g_state_mutex);
            lc_drive_fault_shutdown();
        }

        /* ── ND settle tick ────────────────────────────────── */
        nd_tick_10ms();

        /* ── PID task lifecycle ────────────────────────────── */
        xSemaphoreTake(g_state_mutex, portMAX_DELAY);
        uint8_t mode = g_nd.mode;
        xSemaphoreGive(g_state_mutex);

        if (mode == 2 && s_pid_task_handle == NULL) {
            xTaskCreate(pid_task_fn, "PID", 64, NULL, 3,
                        &s_pid_task_handle);
        } else if (mode != 2 && s_pid_task_handle != NULL) {
            vTaskDelete(s_pid_task_handle);
            s_pid_task_handle = NULL;
        }
    }
}

/*
 * sensor_task — 100 ms periodic.
 *
 * Reads TMP117 temperature, updates g_nd.temp_decidegc,
 * sets/clears TEMP_WARN and triggers fault shutdown on TEMP_CRIT.
 */
static void sensor_task(void *arg)
{
    TickType_t last_wake = xTaskGetTickCount();
    int16_t temp_decidegc;
    (void)arg;

    for (;;) {
        vTaskDelayUntil(&last_wake, pdMS_TO_TICKS(100));

        xSemaphoreTake(g_i2c_mutex, portMAX_DELAY);
        bool ok = tmp117_read_decidegc(&temp_decidegc);
        xSemaphoreGive(g_i2c_mutex);

        if (!ok)
            continue;   /* I2C error — keep last known temperature */

        xSemaphoreTake(g_state_mutex, portMAX_DELAY);
        g_nd.temp_decidegc = temp_decidegc;

        if (temp_decidegc >= TEMP_CRIT_DECIDEGC) {
            /*
             * Critical temperature: disable drive immediately.
             * Set both TEMP_WARN and DC_FAULT so the host knows
             * why the drive was cut.  Host must send a recovery
             * command after the cell has cooled.
             */
            g_nd.status |= STATUS_TEMP_WARN | STATUS_DC_FAULT;
            xSemaphoreGive(g_state_mutex);
            lc_drive_fault_shutdown();
        } else if (temp_decidegc >= TEMP_WARN_DECIDEGC) {
            g_nd.status |=  STATUS_TEMP_WARN;
            xSemaphoreGive(g_state_mutex);
        } else {
            g_nd.status &= (uint8_t)~STATUS_TEMP_WARN;
            xSemaphoreGive(g_state_mutex);
        }
    }
}
